/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import  { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from 'react-three-fiber'
import { a } from '@react-spring/three'

import homeofficeScene from '../assets/3D/homeoffice.glb'

const Homeoffice = (props) =>{
    const homeofficeRef = useRef();

    const { nodes, materials } = useGLTF('homeofficeScene')
    return (
    <a.group ref={homeofficeRef} {...props}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          
          
          geometry={nodes.SM_Bld_Door_05__1_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[236.599, 74.998, 0]}
          rotation={[0, 0, 1.571]}
        />
        <mesh
          
          
          geometry={nodes.SM_Bld_Floor_Carpet_01__19_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-0.002, -250.001, 0]}
        />
        <mesh
          
          
          geometry={nodes.SM_Bld_Floor_Carpet_01__20_.geometry}
          material={materials.PolygonOffice_Material_01_A}
        />
        <mesh
          
          
          geometry={nodes.SM_Bld_Floor_Carpet_01__47_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-250.001, -249.999, 0]}
        />
        <mesh
          
          
          geometry={nodes.SM_Bld_Floor_Carpet_01__48_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-250.001, 0, 0]}
        />
        <mesh
          
          
          geometry={nodes.SM_Bld_Pillar_Exterior_04__10_.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[249.999, 250.001, 0]}
          rotation={[0, 0, -1.571]}
        />
        <mesh
          
          
          geometry={nodes.SM_Bld_Pillar_Exterior_04__11_.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[249.998, -250.002, 0]}
          rotation={[0, 0, -Math.PI]}
        />
        <mesh
          
          
          geometry={nodes.SM_Bld_Pillar_Exterior_04__8_.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-250.002, -250.001, 0]}
          rotation={[0, 0, 1.571]}
        />
        <mesh
          
          
          geometry={nodes.SM_Bld_Pillar_Exterior_04__9_.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-250.001, 249.999, 0]}
        />
        <mesh
          
          
          geometry={nodes.SM_Bld_Wall_Baseboard_01__132_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[249.999, 250.003, 0]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          
          
          geometry={nodes.SM_Bld_Wall_Baseboard_01__136_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[0, 249.999, 0]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          
          
          geometry={nodes.SM_Bld_Wall_Baseboard_01__144_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[249.998, -250.002, 0]}
          rotation={[0, 0, 1.571]}
        />
        <mesh
          
          
          geometry={nodes.SM_Bld_Wall_Baseboard_01__145_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-250.001, 250.002, 0]}
        />
        <mesh
          
          
          geometry={nodes.SM_Bld_Wall_Baseboard_01__146_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[0, 250, 0]}
        />
        <mesh
          
          
          geometry={nodes.SM_Bld_Wall_Baseboard_01__149_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[250, 0, 0]}
          rotation={[0, 0, -1.571]}
        />
        <mesh
          
          
          geometry={nodes.SM_Bld_Wall_Baseboard_Door_01__3_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[249.999, -0.002, 0]}
          rotation={[0, 0, 1.571]}
        />
        <mesh
          
          
          geometry={nodes.SM_Bld_Wall_Baseboard_Door_01__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[249.999, 250.001, 0]}
          rotation={[0, 0, -1.571]}
        />
        <mesh
          
          
          geometry={nodes.SM_Bld_Wall_Baseboard_Window_01__10_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-250.002, -250.001, 0]}
          rotation={[0, 0, Math.PI / 2]}>
          <mesh
            
            
            geometry={nodes.SM_Bld_Wall_Baseboard_Window_01_Glass_4.geometry}
            material={materials.PolygonOffice_Material_Glass}
          />
        </mesh>
        <mesh
          
          
          geometry={nodes.SM_Bld_Wall_Baseboard_Window_01__11_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-250.001, 0, 0]}
          rotation={[0, 0, Math.PI / 2]}>
          <mesh
            
            
            geometry={nodes.SM_Bld_Wall_Baseboard_Window_01_Glass_5.geometry}
            material={materials.PolygonOffice_Material_Glass}
          />
        </mesh>
        <mesh
          
          
          geometry={nodes.SM_Bld_Wall_Baseboard_Window_01__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-0.002, -250.001, 0]}>
          <mesh
            
            
            geometry={nodes.SM_Bld_Wall_Baseboard_Window_01_Glass.geometry}
            material={materials.PolygonOffice_Material_Glass}
          />
        </mesh>
        <mesh
          
          
          geometry={nodes.SM_Bld_Wall_Baseboard_Window_01__5_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-250.002, -250.001, 0]}>
          <mesh
            
            
            geometry={nodes.SM_Bld_Wall_Baseboard_Window_01_Glass_1.geometry}
            material={materials.PolygonOffice_Material_Glass}
          />
        </mesh>
        <mesh
          
          
          geometry={nodes.SM_Bld_Wall_Baseboard_Window_01__6_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-250.001, 0, 0]}
          rotation={[0, 0, -1.571]}>
          <mesh
            
            
            geometry={nodes.SM_Bld_Wall_Baseboard_Window_01_Glass_2.geometry}
            material={materials.PolygonOffice_Material_Glass}
          />
        </mesh>
        <mesh
          
          
          geometry={nodes.SM_Bld_Wall_Baseboard_Window_01__7_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-250.001, 249.999, 0]}
          rotation={[0, 0, -1.571]}>
          <mesh
            
            
            geometry={nodes.SM_Bld_Wall_Baseboard_Window_01_Glass_3.geometry}
            material={materials.PolygonOffice_Material_Glass}
          />
        </mesh>
        <mesh
          
          
          geometry={nodes.SM_Bld_Wall_Baseboard_Window_01__8_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[249.998, -250.002, 0]}
          rotation={[0, 0, Math.PI]}>
          <mesh
            
            
            geometry={nodes.SM_Bld_Wall_Baseboard_Window_01_Glass_6.geometry}
            material={materials.PolygonOffice_Material_Glass}
          />
        </mesh>
        <mesh
          
          
          geometry={nodes.SM_Bld_Wall_Baseboard_Window_01__9_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-0.002, -250.001, 0]}
          rotation={[0, 0, Math.PI]}>
          <mesh
            
            
            geometry={nodes.SM_Bld_Wall_Baseboard_Window_01_Glass_7.geometry}
            material={materials.PolygonOffice_Material_Glass}
          />
        </mesh>
        <mesh
          
          
          geometry={nodes.SM_Prop_AirVent_Wall_01__3_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-236.1, 123.199, -280.8]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[1, 1, 0.634]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_AirVent_Wall_01__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-236.1, -126.101, -280.8]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[1, 1, 0.634]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Bin_02__11_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[12.8, 185, 0]}
          rotation={[0, 0, 0.605]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Book_Group_01__3_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[212.81, -184.929, -122.3]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.897}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Book_Group_01__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[210.5, 11.201, -6.202]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.897}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Book_Group_02__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[213.91, -149.729, -93.4]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.813}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Book_Group_02__5_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[214.96, -40.189, -62.05]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.813}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Book_Group_03__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[212.611, -182.129, -63.103]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.833}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Book_Group_03__5_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[214, -38.899, -34.105]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.833}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Book_Group_04__5_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[215.841, -131.659, -122.64]}
          rotation={[0, 0, -1.364]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Book_Group_04__6_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[216.1, 37.601, -89.289]}
          rotation={[0, 0, -1.571]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Book_Group_08__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[212.49, -58.879, -6.202]}
          rotation={[0, 0, 1.38]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Book_Group_08__5_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[214.91, -207.629, -93]}
          rotation={[0, 0, 1.302]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Book_Magazine_01__5_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-109.35, 71.79, -43.5]}
          rotation={[0, 0.095, 0]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Book_Magazine_02__7_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-95.328, 71.707, -41.6]}
          rotation={[0, 0, -0.975]}
        />
        <group position={[-153.536, -79.307, -75]} rotation={[0, 0, -1.047]}>
          <mesh
            
            
            geometry={nodes.Scene080.geometry}
            material={materials.PolygonOffice_Material_01_A}
          />
          <mesh
            
            
            geometry={nodes.Scene080_1.geometry}
            material={materials.PolygonOffice_Material_Glass}
          />
        </group>
        <mesh
          
          
          geometry={nodes.SM_Prop_Briefcase_01__2_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-174.7, -30.8, 0]}
          rotation={[0, 0, -0.129]}>
          <mesh
            
            
            geometry={nodes.SM_Prop_Briefcase_Lid_01.geometry}
            material={materials.PolygonOffice_Material_01_A}
          />
        </mesh>
        <mesh
          
          
          geometry={nodes.SM_Prop_Cabinets_02__1_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[89.3, -196.6, 0]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_CardboardBox_03__2_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[70.4, 189.2, -1.1]}
          rotation={[0, 0, -0.889]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_CardboardBox_04__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-160.4, 167.6, -45.2]}
          rotation={[0, 0, -0.148]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Cellphone_01__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-146.769, -149.152, -74.24]}
          rotation={[0, 0, 0.346]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Certificate_01__5_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[236.462, -180.999, -194.4]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Chair_07__6_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-65.312, -105.24, 0]}
          rotation={[0, 0, 2.112]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Clock_01__9_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-237.8, 1.299, -219.7]}
          rotation={[0, 0, -Math.PI / 2]}>
          <mesh
            
            
            geometry={nodes.SM_Prop_Clock_01_Hand_01.geometry}
            material={materials.PolygonOffice_Material_01_A}
            position={[0, 4.27, 0]}
            rotation={[-0.012, 0.709, 0.053]}
          />
          <mesh
            
            
            geometry={nodes.SM_Prop_Clock_01_Hand_02.geometry}
            material={materials.PolygonOffice_Material_01_A}
            position={[0, 4.27, 0]}
            rotation={[0, -0.424, 0]}
          />
        </mesh>
        <mesh
          
          
          geometry={nodes.SM_Prop_CoffeeTable_01__4_.geometry}
          material={materials.PolygonOffice_Material_04_A}
          position={[-127.6, 62.4, 0]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Computer_Keyboard_01__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-134.918, -122.68, -75]}
          rotation={[0, 0, -1.047]}
        />
        <group position={[-174.593, -162.561, -75]} rotation={[0, 0, -1.047]}>
          <mesh
            
            
            geometry={nodes.Scene088.geometry}
            material={materials.PolygonOffice_Material_01_A}
          />
          <mesh
            
            
            geometry={nodes.Scene088_1.geometry}
            material={materials.PolygonOffice_Material_Screen_01}
          />
        </group>
        <group position={[-113.786, -216.481, -75]} rotation={[0, 0, -0.351]}>
          <mesh
            
            
            geometry={nodes.Scene087.geometry}
            material={materials.PolygonOffice_Material_01_A}
          />
          <mesh
            
            
            geometry={nodes.Scene087_1.geometry}
            material={materials.PolygonOffice_Material_Screen_04}
          />
        </group>
        <group position={[-190.484, -86.609, -75]} rotation={[0, 0, -1.692]}>
          <mesh
            
            
            geometry={nodes.Scene087.geometry}
            material={materials.PolygonOffice_Material_01_A}
          />
          <mesh
            
            
            geometry={nodes.Scene087_1.geometry}
            material={materials.PolygonOffice_Material_Screen_04}
          />
        </group>
        <mesh
          
          
          geometry={nodes.SM_Prop_Computer_Mouse_01__3_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-109.296, -171.858, -75.5]}
          rotation={[0, 0, -1.645]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Computer_Mousepad_02__2_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-106.657, -174.028, -75]}
          rotation={[0, 0, -1.047]}
          scale={[0.798, 0.76, 1]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Computer_Tower_Modern_01__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-177.6, -69.5, 0]}
          rotation={[0, 0, -1.571]}>
          <mesh
            
            
            geometry={nodes.SM_Prop_Computer_Tower_Modern_Glass_01.geometry}
            material={materials.PolygonOffice_Material_Glass}
            position={[-2.293, 0.946, -31.403]}
          />
        </mesh>
        <mesh
          
          
          geometry={nodes.SM_Prop_Console_MegaCube_01__1_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[210.71, -124.33, -63.01]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Console_PlayBox_01__1_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[216.9, -102.346, -169.5]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[1, 1, 1.303]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Controller_01__3_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[210.1, -197.099, -122.68]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Controller_01__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[73.381, -171.81, -75.54]}
          rotation={[0, 0, 0.298]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Cord_Desk_01__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-209.11, -150.101, 0]}
          rotation={[0, 0, -1.589]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Cord_Wall_01__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-70.45, -198.2, -1.265]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Couch_02__3_.geometry}
          material={materials.PolygonOffice_Material_04_A}
          position={[-111.6, 186.6, 0]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Cup_Boss_01__2_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-106.015, -189.939, -75.54]}
          rotation={[0, 0, -0.465]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Cup_Coffee_Disposable_Open_Full_01__2_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-89.662, 43.986, -41.86]}
          rotation={[0, 0, -0.713]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Cup_Lid_01__2_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[110, -168.6, -75.48]}
          rotation={[0, 0, 1.985]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Cup_Pens_01__1_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-172.98, -122.58, -74.46]}
          rotation={[0, 0, 0.986]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Darkboard_01__3_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[0.401, -236.2, -191.7]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Desk_01__2_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-148.572, -148.23, 0]}
          rotation={[0, 0, -1.047]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Desk_02__4_.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-130.5, -132.7, 0]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Desklamp_03.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-158.5, -47.9, -74.97]}
          rotation={[0, 0, -2.248]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Donut_Pink_02.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-155.722, 85.579, -42.07]}
          rotation={[0, 0, -0.819]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_FaxMachine_01__2_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-153.5, 54.4, -42.29]}
          rotation={[0, 0, -2.804]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Figure_Cowgirl_01__3_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[213.9, -96.399, -235.39]}
          rotation={[0, 0, 0.99]}
          scale={1.148}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Figure_Goblin_01__2_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[217.5, -16.099, -235.39]}
          rotation={[0, 0, 1.559]}
          scale={1.148}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Figure_Knight_01__2_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[214.387, 19.301, -202.64]}
          rotation={[0, 0, 1.302]}
          scale={1.148}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Figure_Viking_01__3_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-167.7, -92.3, -75.1]}
          rotation={[0, 0, -1.92]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Figure_Viking_01__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[215.16, -122.699, -202.64]}
          rotation={[0, 0, 1.874]}
          scale={1.148}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Flash_Drive_01.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-62.8, -158.86, -74.95]}
          rotation={[0, 0, -0.764]}
          scale={1.09}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_FolderTray_03__1_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[213.9, 27.301, -61.8]}
          rotation={[0, 0, 0.171]}
          scale={[0.845, 0.91, 0.91]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_FootRest_01__2_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-162.299, -166.7, 0]}
          rotation={[0, 0, -1.016]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Globe_01.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[92.901, -193.5, -75]}
        />
        <group position={[-54.1, -176.2, -74.2]} rotation={[0, 0, 0.293]} scale={0.632}>
          <mesh
            
            
            geometry={nodes.Scene034.geometry}
            material={materials.PolygonOffice_Material_01_A}
          />
          <mesh
            
            
            geometry={nodes.Scene034_1.geometry}
            material={materials.PolygonOffice_Material_Screen_01}
          />
        </group>
        <mesh
          
          
          geometry={nodes.SM_Prop_GraphicsTablet_Stylus_01__1_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-77.039, -164.05, -87.81]}
          rotation={[1.59, -0.109, 0.124]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_GraphicsTablet_StylusStand_01__1_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-78.089, -163.8, -74.91]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_HDD_01__1_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[213.2, 26.201, -33.89]}
          scale={1.24}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_HDD_Dock_01__1_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[211.1, 4.301, -88.9]}
          rotation={[0, 0, 0.823]}
          scale={0.788}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Headset_01.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[224.1, -48.189, -213.44]}
          rotation={[0, -0.783, Math.PI / 2]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_HolePunch_01.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-118, 39.6, -42.38]}
          rotation={[0, 0, 2.832]}>
          <mesh
            
            
            geometry={nodes.SM_Prop_HolePunch_01_Lever_01.geometry}
            material={materials.PolygonOffice_Material_01_A}
            position={[0, 4.438, -4.92]}
          />
        </mesh>
        <mesh
          
          
          geometry={nodes.SM_Prop_ID_Card_01__2_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-169.8, -72.4, -75.12]}
          rotation={[0, 0, -2.311]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Microphone_03__1_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-132.82, -170.313, -75]}
          rotation={[0, 0, -0.498]}
          scale={0.789}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Mints_01__2_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-185.22, -45.21, -75]}
          rotation={[0, 0, -1.047]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Modem_04.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[212.7, 13.501, -169.4]}
          rotation={[0, 0, Math.PI / 3]}
          scale={1.381}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Neon_Cactus_01.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[219.4, 45.501, -200.9]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Plant_02__1_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-43.199, -204.357, -70.7]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Plant_03__3_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[219, -27.999, -89.289]}
          rotation={[0, 0, -1.571]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Plant_04__6_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-179.803, 3.739, 0]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Plant_13__2_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[19.001, -175.4, 0]}
          scale={[0.839, 0.872, 1]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Poster_01__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[84.399, 236.2, -220.4]}
          rotation={[0, 0, Math.PI]}
          scale={1.224}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_PuzzleCube_01__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[216.57, -70.359, -88.898]}
          rotation={[0, 0, -2.039]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Rug_02__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[102.174, 22.142, 2]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Shelf_05__1_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[215.01, -167.829, 0]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Shelf_06__3_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[216.7, -14.599, 0]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Shelf_Wall_02.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[243.8, -47.099, -169.9]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Socket_Switch_01__13_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[233.6, 205.201, -125]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Socket_Wall_02__44_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[149.999, 232.9, -25]}
          rotation={[0, 0, -Math.PI]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Socket_Wall_02__45_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-232.1, 106.399, -25]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Speaker_Bluetooth_02__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[211.2, -50.299, -169.4]}
          rotation={[0, 0, 1.675]}
          scale={1.249}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Trophy_01__1_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[215.156, -207.729, -151.91]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_Trophy_01__2_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[215.156, -175.599, -150]}
          rotation={[0, 0, 0.922]}
          scale={0.805}
        />
        <mesh
          
          
          geometry={nodes.SM_Prop_WallDressing_03__4_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-97.301, 237.1, -120.1]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          
          
          geometry={nodes.SM_Wep_ToyGun_Shotgun_01__1_.geometry}
          material={materials.PolygonOffice_Material_01_A}
          position={[-161.168, -210.813, -77.11]}
          rotation={[Math.PI / 2, -0.594, -Math.PI / 2]}>
          <mesh
            
            
            geometry={nodes.SM_Wep_ToyGun_Shotgun_01_Handle_01.geometry}
            material={materials.PolygonOffice_Material_01_A}
            position={[0, 12.187, 0.431]}
          />
          <mesh
            
            
            geometry={nodes.SM_Wep_ToyGun_Shotgun_01_Trigger_01.geometry}
            material={materials.PolygonOffice_Material_01_A}
            position={[0, 8.054, -0.025]}
          />
        </mesh>
      </group>
    </a.group>
  )
}

useGLTF.preload('/homeofficeNoTex.glb')

export default Homeoffice;